# Generated by Django 2.2.1 on 2021-01-25 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='SSN',
            new_name='ssn',
        ),
    ]
