# Generated by Django 2.2.1 on 2021-01-26 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210125_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=14, null=True)),
                ('university_id', models.CharField(max_length=20, null=True)),
                ('level', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='info',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='matrial',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='matrial',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='result',
            name='quiz_id',
        ),
        migrations.RemoveField(
            model_name='result',
            name='user_id',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matrial',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to='users.Course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='users.Course'),
        ),
        migrations.AddField(
            model_name='result',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_details', to='users.Quiz'),
        ),
        migrations.AddField(
            model_name='result',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=jsonfield.fields.JSONField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Course_enrolled',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
