# Generated by Django 2.2 on 2021-01-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210129_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrial',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
