# Generated by Django 2.2 on 2021-02-04 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_matrial_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_by_instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
