# Generated by Django 2.2 on 2021-02-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210204_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
